apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: db
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: db
    release: {{ .Release.Name }}
